// Code generated by "stringer -type=AbortReason"; DO NOT EDIT.

package specs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OtherAbortReason-0]
	_ = x[BufferOverflowAbortReason-1]
	_ = x[InvalidAPDUInThisStateAbortReason-2]
	_ = x[PreemptedByHigherPriorityTaskAbortReason-3]
	_ = x[SegmentationNotSupportedAbortReason-4]
	_ = x[SecurityErrorAbortReason-5]
	_ = x[InsufficientSecurityAbortReason-6]
	_ = x[WindowSizeOutOfRangeAbortReason-7]
	_ = x[ApplicationExceededReplyTimeAbortReason-8]
	_ = x[OutOfResourcesAbortReason-9]
	_ = x[TsmTimeoutAbortReason-10]
	_ = x[APDUTooLongAbortReason-11]
}

const _AbortReason_name = "OtherAbortReasonBufferOverflowAbortReasonInvalidAPDUInThisStateAbortReasonPreemptedByHigherPriorityTaskAbortReasonSegmentationNotSupportedAbortReasonSecurityErrorAbortReasonInsufficientSecurityAbortReasonWindowSizeOutOfRangeAbortReasonApplicationExceededReplyTimeAbortReasonOutOfResourcesAbortReasonTsmTimeoutAbortReasonAPDUTooLongAbortReason"

var _AbortReason_index = [...]uint16{0, 16, 41, 74, 114, 149, 173, 204, 235, 274, 299, 320, 342}

func (i AbortReason) String() string {
	if i >= AbortReason(len(_AbortReason_index)-1) {
		return "AbortReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AbortReason_name[_AbortReason_index[i]:_AbortReason_index[i+1]]
}
